gstbilling/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gstbillingapp.urls')),
    path('', include('social_django.urls', namespace='social'))
]

gstbillingapp/urls.py
from django.urls import path
from django.urls import include

from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),

    path('invoices/new', views.invoice_create, name='invoice_create'),
    path('invoices/delete', views.invoice_delete, name='invoice_delete'),

    path('login', views.login_view, name='login_view'),
    path('signup', views.signup_view, name='signup_view'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('invoices', views.invoices, name='invoices'),
    path('invoice/<int:invoice_id>', views.invoice_viewer, name='invoice_viewer'),

    path('customers', views.customers, name='customers'),
    path('customers/add', views.customer_add, name='customer_add'),
    path('customers/edit/<int:customer_id>', views.customer_edit, name='customer_edit'),
    path('customers/delete', views.customer_delete, name='customer_delete'),
    path('customersjson', views.customersjson, name='customersjson'),

    path('products', views.products, name='products'),
    path('products/add', views.product_add, name='product_add'),
    path('products/edit/<int:product_id>', views.product_edit, name='product_edit'),
    path('products/delete', views.product_delete, name='product_delete'),
    path('productsjson', views.productsjson, name='productsjson'),

    path('inventory', views.inventory, name='inventory'),
    path('inventory/<int:inventory_id>', views.inventory_logs, name='inventory_logs'),
    path('inventory/<int:inventory_id>/addupdate', views.inventory_logs_add, name='inventory_logs_add'),

    path('books', views.books, name='books'),
    path('books/<int:book_id>', views.book_logs, name='book_logs'),
    path('books/<int:book_id>/addupdate', views.book_logs_add, name='book_logs_add'),


    path('profile', views.user_profile, name='user_profile'),
    path('profile/edit', views.user_profile_edit, name='user_profile_edit'),


]

gstbillingapp/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime
# Create your models here.

# ========================== Saas Data models ==================================

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    business_title = models.CharField(max_length=100, blank=True, null=True)
    business_address = models.TextField(max_length=400, blank=True, null=True)
    business_email = models.EmailField(blank=True, null=True)
    business_phone = models.CharField(max_length=20, blank=True, null=True)
    business_gst = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return self.user.username


class Plan(models.Model):
    plan_name = models.TextField(max_length=20, blank=True, null=True)
    plan_value = models.IntegerField(blank=True, null=True)
    monthly_invoice_limit = models.IntegerField(blank=True, null=True)


class BillingProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, blank=True, null=True, on_delete=models.SET_NULL)
    plan_start_date = models.DateField(blank=True, null=True)
    plan_end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.user.username

# ======================= Invoice Data models =================================

class Customer(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    customer_name = models.CharField(max_length=200)
    customer_address = models.TextField(max_length=600, blank=True, null=True)
    customer_phone = models.CharField(max_length=14, blank=True, null=True)
    customer_gst = models.CharField(max_length=15, blank=True, null=True)
    def __str__(self):
        return self.customer_name


class Invoice(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    invoice_number = models.IntegerField()
    invoice_date = models.DateField()
    invoice_customer = models.ForeignKey(
        'Customer',
        on_delete=models.SET_NULL,
        null=True
    )
    invoice_json = models.TextField()
    inventory_reflected = models.BooleanField(default=True)
    books_reflected = models.BooleanField(default=True)
    def __str__(self):
        return str(self.invoice_number) + " | " + str(self.invoice_date)


class Product(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product_name = models.CharField(max_length=200)
    product_hsn = models.CharField(max_length=50, null=True, blank=True)
    product_unit = models.CharField(max_length=50)
    product_gst_percentage = models.FloatField()
    product_rate_with_gst = models.FloatField()
    def __str__(self):
        return str(self.product_name)

# ========================= Inventory Data models ====================================
class InventoryLog(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True)
    change = models.IntegerField(default=0)
    CHANGE_TYPES = [
        (0, 'Other'),
        (1, 'Purchase'),
        (2, 'Production'),
        (4, 'Sales'),
    ]
    change_type = models.IntegerField(choices=CHANGE_TYPES, default=0)

    associated_invoice = models.ForeignKey(Invoice, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    description = models.TextField(max_length=600, blank=True, null=True)

    def __str__(self):
        return self.product.product_name + " | " + str(self.change) + " | " + self.description + " | " + str(self.date)

class Inventory(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL)
    current_stock = models.IntegerField(default=0)
    alert_level = models.IntegerField(default=0)
    last_log = models.ForeignKey(InventoryLog, null=True, blank=True, default=None, on_delete=models.SET_NULL)

    def __str__(self):
        return self.product.product_name

# ========================= Books Data models ======================================

class Book(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    current_balance = models.FloatField(default=0)
    last_log = models.ForeignKey('BookLog', null=True, blank=True, default=None, on_delete=models.SET_NULL)

    def __str__(self):
        return self.customer.customer_name


class BookLog(models.Model):
    parent_book = models.ForeignKey(Book, null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True)
    CHANGE_TYPES = [
        (0, 'Paid'),
        (1, 'Purchased Items'),
        (2, 'Sold Items'),
        (4, 'Other'),
    ]
    change_type = models.IntegerField(choices=CHANGE_TYPES, default=0)
    change = models.FloatField(default=0.0)

    associated_invoice = models.ForeignKey(Invoice, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    description = models.TextField(max_length=600, blank=True, null=True)

    def __str__(self):
        return self.parent_book.customer.customer_name + " | " + str(self.change) + " | " + self.description + " | " + str(self.date)


gstbillingapp/forms.py
from django.forms import ModelForm
from .models import Customer
from .models import Product
from .models import UserProfile
from .models import InventoryLog
from .models import BookLog


class CustomerForm(ModelForm):
     class Meta:
         model = Customer
         fields = ['customer_name', 'customer_address', 'customer_phone', 'customer_gst']


class ProductForm(ModelForm):
     class Meta:
         model = Product
         fields = ['product_name', 'product_hsn', 'product_unit', 'product_gst_percentage', 'product_rate_with_gst']


class UserProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(UserProfileForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['business_title'].required = True

    class Meta:
        model = UserProfile
        fields = ['business_title', 'business_address', 'business_email', 'business_phone', 'business_gst']


class InventoryLogForm(ModelForm):
    class Meta:
        model = InventoryLog
        fields = ['date', 'change', 'change_type', 'description']


class BookLogForm(ModelForm):
    class Meta:
        model = BookLog
        fields = ['date', 'change', 'change_type', 'description']

gstbillingapp/templates/gstbillingapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>
		{% block title %}
		GST Billing
		{% endblock %}
	</title>

	{% block metatags %}
	{% endblock %}



	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static "gstbillingapp/bootstrap-4.4.1-dist/css/bootstrap-cosmo.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/main.css" %}">
	<link rel="icon" type="image/x-icon" href="{% static 'gstbillingapp/images/cropped-M-favicon-01.webp' %}">

	<!-- DataTables CSS  -->
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/jquery.dataTables.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/dataTables.bootstrap4.min.css" %}">

	{% block includecss %}
	{% endblock %}

</head>

<body>

	<div class="container">
		<!-- Content here -->

		{% include "gstbillingapp/navbar.html" %}

		{% if error_message %}
		<div class="alert alert-danger" role="alert">
			{{error_message}}
		</div>
		{% endif %}

		{% if success_message %}
		<div class="alert alert-success" role="alert">
			{{success_message}}
		</div>
		{% endif %}

		{% block content %}
		CONTENT BLOCK
		{% endblock %}

		<br>

		
		{% block footer %}
		<footer class="bg-dark text-white text-center py-3">
			© 2024 Mayank | All Rights Reserved | <a href="#" class="text-white">Mayank Prajapati</a>
		</footer>
		
		{% endblock footer %}
			

	</div>




	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	
	<!-- 	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script> -->
	<script src="{% static "gstbillingapp/js/jquery-3.4.1.min.js" %}"></script>
	<script src="{% static "gstbillingapp/js/popper.min.js" %}"></script>

	<script src="{% static "gstbillingapp/bootstrap-4.4.1-dist/js/bootstrap.min.js" %}"></script>

	<!-- DataTables  -->
	<script src="{% static "gstbillingapp/DataTables/jquery.dataTables.min.js" %}"></script>


	{% block includejs %}
	{% endblock %}



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-159304253-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-159304253-1');
</script>



</body>


</html>

gstbillingapp/templates/gstbillingapp/book_logs.html
{% extends "gstbillingapp/base.html" %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-primary font-weight-bold text-center">Book Details</h2>
    <hr>
    <div class="row mb-4">
        <div class="col-lg-8">
            <h3><span class="font-weight-bold">Customer:</span> {{book.customer.customer_name}}</h3>
            <h3><span class="font-weight-bold">Current Balance:</span> {{book.current_balance}}</h3>
        </div>
        <div class="col-lg-4 text-lg-right text-center mt-3 mt-lg-0">
            <a href="{% url 'book_logs_add' book.id %}" class="btn btn-primary btn-lg">Add Update</a>
        </div>
    </div>
    <hr>
    <div class="card shadow-lg">
        <div class="card-body">
            <table class="table table-hover table-striped" id="inventory-logs-table">
                <thead class="thead-light">
                    <tr>
                        <th>Date</th>
                        <th>Type</th>
                        <th>Description</th>
                        <th class="text-right">Change</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in book_logs %}
                    <tr class="{% if item.change < 0 %}table-danger{% else %}table-success{%endif%}">
                        <td>{{item.date}}</td>
                        <td>{{item.get_change_type_display}} {% if item.associated_invoice %}<a href="{% url 'invoice_viewer' item.associated_invoice.id %}" class="text-info font-weight-bold">[INVOICE]</a>{% endif %}</td>
                        <td>{{item.description}}</td>
                        <td class="text-right">{{item.change}} &emsp; {{inventory.product.product_unit}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block includejs %}
<script type="text/javascript">
$(document).ready(function () {
    $('#inventory-logs-table').DataTable({
        "order": [],
        "paging": true,
        "searching": true,
        "info": true,
    });
});
</script>
{% endblock %}

{% block styles %}
<style>
h2 {
    color: #007bff;
}

h3 {
    color: #333;
}

.card {
    border-radius: 10px;
}

.card-body {
    background-color: #f8f9fa;
}

.table {
    table-layout: fixed;
    width: 100%;
}

.table th, .table td {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
    vertical-align: middle;
}

.table th {
    text-align: center;
}

.table .text-right {
    text-align: right;
}

.table-danger, .table-success {
    color: #fff;
}

.table-danger {
    background-color: #e74c3c !important;
}

.table-success {
    background-color: #2ecc71 !important;
}
</style>
{% endblock %}

gstbillingapp/templates/gstbillingapp/book_logs_add.html
{% extends "gstbillingapp/base.html" %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-primary font-weight-bold text-center">Update Book</h2>
    <hr>
    <div class="row mb-4">
        <div class="col-lg-8">
            <h3><span class="font-weight-bold">Customer:</span> {{book.customer.customer_name}}</h3>
            <h3><span class="font-weight-bold">Current Balance:</span> {{book.current_balance}}</h3>
        </div>
    </div>
    <div class="card shadow-lg border-0">
        <div class="card-body p-4">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group row mb-3">
                    <label for="{{ form.date.id_for_label }}" class="col-md-4 col-form-label text-md-right font-weight-bold">Date & Time:</label>
                    <div class="col-md-8">
                        {{ form.date }}
                    </div>
                </div>
                <div class="form-group row mb-3">
                    <label for="{{ form.change.id_for_label }}" class="col-md-4 col-form-label text-md-right font-weight-bold">Change in Balance:</label>
                    <div class="col-md-8">
                        {{ form.change }}
                    </div>
                </div>
                <div class="form-group row mb-3">
                    <label for="{{ form.change_type.id_for_label }}" class="col-md-4 col-form-label text-md-right font-weight-bold">Change Type:</label>
                    <div class="col-md-8">
                        {{ form.change_type }}
                    </div>
                </div>
                <div class="form-group row mb-3">
                    <label for="invoice_no" class="col-md-4 col-form-label text-md-right font-weight-bold">Associated Invoice Number:</label>
                    <div class="col-md-8">
                        <input type="text" name="invoice_no" class="form-control" id="invoice_no">
                    </div>
                </div>
                <div class="form-group row mb-4">
                    <label for="{{ form.description.id_for_label }}" class="col-md-4 col-form-label text-md-right font-weight-bold">Description:</label>
                    <div class="col-md-8">
                        {{ form.description }}
                    </div>
                </div>
                <div class="row">
                    <div class="col text-center">
                        <input type="submit" class="btn btn-success btn-lg px-5" value="Submit">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br><br>
{% endblock %}

{% block styles %}
<style>
h2 {
    color: #007bff;
}

h3 {
    color: #333;
}

.card {
    border-radius: 10px;
}

.card-body {
    background-color: #f8f9fa;
}

.form-group label {
    font-weight: bold;
}

.btn-success {
    background-color: #28a745;
    border-color: #28a745;
}

.btn-success:hover {
    background-color: #218838;
    border-color: #1e7e34;
}
</style>
{% endblock %}

gstbillingapp/templates/gstbillingapp/books.html
{% extends "gstbillingapp/base.html" %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h2 class="text-primary font-weight-bold">Customer Book</h2>
        </div>
    </div>

    <div class="card shadow-lg mt-4">
        <div class="card-body p-4">
            <table class="table table-hover table-striped" id="book-table">
                <thead class="thead-light">
                    <tr>
                        <th>Customer</th>
                        <th>Current Balance</th>
                        <th>Last Transaction</th>
                    </tr>
                </thead>
                <tbody>
                    {% for book in book_list %}
                    <tr onclick="window.location='{% url 'book_logs' book.id %}';" style="cursor:pointer;">
                        <td><a href="{% url 'book_logs' book.id %}" class="text-dark">{{book.customer.customer_name}}</a></td>
                        <td>{{book.current_balance}}</td>
                        <td>{{book.last_log}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block includejs %}
<script type="text/javascript">
$(document).ready(function () {
    $('#book-table').DataTable({
        "order": [],
        "paging": true,
        "searching": true,
        "info": true,
    });
});
</script>
{% endblock %}

{% block styles %}
<style>
.table {
    table-layout: fixed;
    width: 100%;
}

.table th, .table td {
    text-overflow: ellipsis;
    white-space: nowrap;
    vertical-align: middle;
}

.table th, .table td a {
    color: #007bff;
    font-weight: bold;
}

.table th {
    text-align: center;
}

.card {
    border-radius: 10px;
}

.card-body {
    background-color: #f8f9fa;
}

h2 {
    color: #007bff;
}
</style>
{% endblock %}

gstbillingapp/templates/gstbillingapp/customer_edit.html
{% extends "gstbillingapp/base.html" %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card shadow-lg border-0">
                <div class="card-header bg-gradient-primary text-white text-center py-4">
                    <h3 style="color: black;">Edit Customer</h3>
                </div>
                <div class="card-body p-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <label for="{{ customer_form.customer_name.id_for_label }}" class="col-md-4 text-right font-weight-bold">Customer Name:</label>
                            <div class="col-md-8">
                                {{ customer_form.customer_name }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="{{ customer_form.customer_address.id_for_label }}" class="col-md-4 text-right font-weight-bold">Customer Address:</label>
                            <div class="col-md-8">
                                {{ customer_form.customer_address }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="{{ customer_form.customer_phone.id_for_label }}" class="col-md-4 text-right font-weight-bold">Customer Phone:</label>
                            <div class="col-md-8">
                                {{ customer_form.customer_phone }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="{{ customer_form.customer_gst.id_for_label }}" class="col-md-4 text-right font-weight-bold">Customer GST:</label>
                            <div class="col-md-8">
                                {{ customer_form.customer_gst }}
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col text-center">
                                <input type="submit" class="btn btn-success btn-lg px-5" value="Save Changes">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

gstbillingapp/templates/gstbillingapp/customers.html
{% extends "gstbillingapp/base.html" %}

{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row mb-3">
        <div class="col-md-6">
            <h2 class="text-primary">Customers</h2>
        </div>
        <div class="col-md-6 text-md-right">
            <a href="{% url 'customer_add' %}" id="add_customer_btn">
                <button type="button" class="btn btn-success btn-lg">Add New Customer</button>
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <table class="table table-hover" id="customer-table">
                <thead class="thead-light">
                    <tr>
                        <th class="text-nowrap">Customer Name</th>
                        <th class="text-nowrap">Address</th>
                        <th class="text-nowrap">Phone</th>
                        <th class="text-nowrap">GST NO</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for customer in customers %}
                    <tr>
                        <td>{{ customer.customer_name }}</td>
                        <td>{{ customer.customer_address }}</td>
                        <td>{{ customer.customer_phone }}</td>
                        <td>{{ customer.customer_gst }}</td>
                        <td class="text-center">
                            <a href="{% url 'customer_edit' customer.id %}" class="btn btn-warning btn-sm">Edit</a>
                            <button type="button" class="btn btn-danger btn-sm ml-2" data-toggle="modal" data-target="#customerDeleteModal" data-customer-id="{{ customer.id }}" data-customer-name="{{ customer.customer_name }}">Delete</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="customerDeleteModal" tabindex="-1" role="dialog" aria-labelledby="customerDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger text-white">
                <h5 class="modal-title" id="customerDeleteModalLabel">Confirm Deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{% url 'customer_delete' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <p>Are you sure you want to delete <strong><span class="customer-name"></span></strong>?</p>
                    <input type="hidden" name="customer_id">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
<br><br><br>
{% endblock %}

{% block includejs %}
<script type="text/javascript">
$('#customerDeleteModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var customer_id = button.data('customer-id')
    var customer_name = button.data('customer-name')
    var modal = $(this)
    modal.find('.modal-body input').val(customer_id)
    modal.find('.customer-name').text(customer_name)
})

$(document).ready(function () {
    $('#customer-table').DataTable({
        "order": [],
        "columnDefs": [
            {
                "targets": 4,
                "sortable": false,
                "searchable": false
            }
        ],
        "paging": true,
        "searching": true,
        "info": true
    });
});
</script>
{% endblock %}

{% block styles %}
<style>
.table {
    table-layout: fixed;
    width: 100%;
}

.table th, .table td {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    vertical-align: middle;
}

.table th {
    width: 15%; /* Adjust as needed */
}

.table td {
    width: 15%; /* Adjust as needed */
}

.table .btn {
    width: auto;
}
</style>
{% endblock %}

gstbillingapp/templates/gstbillingapp/inventory_logs.html
{% extends "gstbillingapp/base.html" %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row mb-4">
        <div class="col">
            <h2 class="text-primary font-weight-bold text-center">Inventory Details</h2>
        </div>
    </div>

    <div class="card shadow-lg border-0 mb-4">
        <div class="card-body p-4">
            <div class="row">
                <div class="col-md-8">
                    <h4 class="font-weight-bold">Product: <span class="text-muted">{{inventory.product}}</span></h4>
                    <h4 class="font-weight-bold">Current Stock: <span class="text-muted">{{inventory.current_stock}}</span></h4>
                </div>
                <div class="col-md-4 text-md-right text-center mt-3 mt-md-0">
                    <a href="{% url 'inventory_logs_add' inventory.id %}">
                        <button type="button" class="btn btn-success btn-lg">Add Update</button>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="card shadow-lg border-0">
        <div class="card-body p-4">
            <table class="table table-hover table-striped" id="inventory-logs-table">
                <thead class="thead-dark">
                    <tr>
                        <th>Date</th>
                        <th>Type</th>
                        <th>Description</th>
                        <th class="text-right">Change</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in inventory_logs %}
                    <tr class="{% if item.change < 0 %}table-danger{% else %}table-success{%endif%}">
                        <td>{{item.date}}</td>
                        <td>
                            {{item.get_change_type_display}}
                            {% if item.associated_invoice %}
                            <a href="{% url 'invoice_viewer' item.associated_invoice.id %}">[INVOICE]</a>
                            {% endif %}
                        </td>
                        <td>{{item.description}}</td>
                        <td class="text-right">{{item.change}} &emsp; {{inventory.product.product_unit}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block styles %}
<style>
    h2 {
        color: #007bff;
        margin-bottom: 20px;
    }

    .card {
        border-radius: 10px;
    }

    .card-body {
        background-color: #f8f9fa;
    }

    .table-hover tbody tr:hover {
        background-color: #f1f1f1;
    }

    .thead-dark th {
        background-color: #343a40;
        color: #fff;
    }

    .table-danger {
        background-color: #f8d7da;
    }

    .table-success {
        background-color: #d4edda;
    }
</style>
{% endblock %}

{% block includejs %}
<script type="text/javascript">
$(document).ready(function() {
    $('#inventory-logs-table').DataTable({
        "order": [],
        "paging": true,
    });
});
</script>
{% endblock %}